/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestXInterface;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.BevelBorder;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author shibayanmondal
 */
public class AdminLogin extends javax.swing.JFrame {

    int pX, pY;
    
    public AdminLogin() {
        initComponents();
        
        this.setSize(379, 487);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_password = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel_usrnm = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel_login_btn = new javax.swing.JLabel();
        jLabel_go_to_main_menu = new javax.swing.JLabel();
        jLabel_login_logo = new javax.swing.JLabel();
        jLabel_restxname = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jCheckBox_show_pass = new javax.swing.JCheckBox();
        jLabel_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usr_rsz.png"))); // NOI18N
        getContentPane().add(jLabel_password);
        jLabel_password.setBounds(60, 270, 40, 50);

        jPasswordField.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField.setText("password");
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });
        jPasswordField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jPasswordFieldInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(jPasswordField);
        jPasswordField.setBounds(110, 280, 180, 30);

        jLabel_usrnm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_usrnm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        getContentPane().add(jLabel_usrnm);
        jLabel_usrnm.setBounds(60, 230, 40, 40);

        jTextField_username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_username.setText("username");
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_username);
        jTextField_username.setBounds(110, 230, 180, 30);

        jLabel_login_btn.setBackground(new java.awt.Color(0, 102, 255));
        jLabel_login_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel_login_btn.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_login_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_login_btn.setText("Login");
        jLabel_login_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_login_btn.setOpaque(true);
        jLabel_login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_login_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_login_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_login_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_login_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_login_btnMouseReleased(evt);
            }
        });
        getContentPane().add(jLabel_login_btn);
        jLabel_login_btn.setBounds(130, 360, 140, 40);
        jLabel_login_btn.setToolTipText("<html><p>username: sh_sa</p><p>password: shsa</p><p>Register form has not been implemented</p><p>yet due to time constraint</p></html>");

        jLabel_go_to_main_menu.setBackground(new java.awt.Color(204, 153, 0));
        jLabel_go_to_main_menu.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel_go_to_main_menu.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_go_to_main_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_go_to_main_menu.setText("Go to Main Menu");
        jLabel_go_to_main_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_go_to_main_menu.setOpaque(true);
        jLabel_go_to_main_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_go_to_main_menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_go_to_main_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_go_to_main_menuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_go_to_main_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_go_to_main_menuMouseReleased(evt);
            }
        });
        getContentPane().add(jLabel_go_to_main_menu);
        jLabel_go_to_main_menu.setBounds(130, 410, 140, 40);

        jLabel_login_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_login_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        getContentPane().add(jLabel_login_logo);
        jLabel_login_logo.setBounds(130, 90, 120, 120);

        jLabel_restxname.setBackground(new java.awt.Color(153, 255, 153));
        jLabel_restxname.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel_restxname.setForeground(new java.awt.Color(204, 0, 102));
        jLabel_restxname.setText("Welcome to RestX");
        jLabel_restxname.setName(""); // NOI18N
        getContentPane().add(jLabel_restxname);
        jLabel_restxname.setBounds(40, 20, 300, 60);
        jLabel_restxname.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));

        jLabel_minimize.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_minimize.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseReleased(evt);
            }
        });
        getContentPane().add(jLabel_minimize);
        jLabel_minimize.setBounds(300, 0, 40, 30);

        jLabel_close.setBackground(new java.awt.Color(153, 0, 0));
        jLabel_close.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseReleased(evt);
            }
        });
        getContentPane().add(jLabel_close);
        jLabel_close.setBounds(340, 0, 40, 30);

        jCheckBox_show_pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_show_pass.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_show_pass.setText("Show Password");
        jCheckBox_show_pass.setOpaque(false);
        jCheckBox_show_pass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_show_passItemStateChanged(evt);
            }
        });
        jCheckBox_show_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_show_passActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_show_pass);
        jCheckBox_show_pass.setBounds(130, 320, 140, 25);

        jLabel_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login_bg1.jpg"))); // NOI18N
        jLabel_bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_bgMouseDragged(evt);
            }
        });
        jLabel_bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_bgMousePressed(evt);
            }
        });
        getContentPane().add(jLabel_bg);
        jLabel_bg.setBounds(-870, -20, 1430, 1970);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_login_btnMouseClicked
        PreparedStatement p_st;
        ResultSet rs;
        String username = jTextField_username.getText();
        String password = String.valueOf(jPasswordField.getPassword());
        // Creating a select query to check the existence of username and password in the database
        String query = "SELECT * FROM `login_details` WHERE `username` = ? AND `password` = ?";
        try {
            p_st = DBConnect.DBConnect.getConnection().prepareStatement(query);
            
            p_st.setString(1, username);
            p_st.setString(2, password);
            rs = p_st.executeQuery();
            
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Invalid Username or Password!", "Login Error", 2);

                        jTextField_username.setText("username");
                        jPasswordField.setText("password");
                        jTextField_username.setForeground(new Color(204,204,204));
                        jPasswordField.setForeground(new Color(204,204,204));
            }
            else {
                    if (rs.getString("password").equals(password) && rs.getString("username").equals(username)) {
                            new RestXInterface.AdminPanel().setVisible(true);
                            this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Username or Password!", "Login Error", 2);
                        jTextField_username.setText("username");
                        jPasswordField.setText("password");
                        jTextField_username.setForeground(new Color(204,204,204));
                        jPasswordField.setForeground(new Color(204,204,204));
                    }
               
            }
                }
         catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jLabel_login_btnMouseClicked

    private void jLabel_bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bgMousePressed
        pX = evt.getX();
        pY = evt.getY();
    }//GEN-LAST:event_jLabel_bgMousePressed

    private void jLabel_bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bgMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - pX,
            this.getLocation().y + evt.getY() - pY);
    }//GEN-LAST:event_jLabel_bgMouseDragged

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        if (jTextField_username.getText().trim().toLowerCase().equals("username")) {
            jTextField_username.setText("");
            jTextField_username.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
        if (jTextField_username.getText().trim().toLowerCase().equals("")) {
            jTextField_username.setText("username");
            jTextField_username.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void jPasswordFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPasswordFieldInputMethodTextChanged

    }//GEN-LAST:event_jPasswordFieldInputMethodTextChanged

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        String myPass = String.valueOf(jPasswordField.getPassword());
        if (myPass.trim().toLowerCase().equals("password")) {
            jPasswordField.setText("");
            jPasswordField.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
         String myPass = String.valueOf(jPasswordField.getPassword());
        if (myPass.equals("")) {
            jPasswordField.setText("password");
            jPasswordField.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void jLabel_login_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_login_btnMouseEntered
        jLabel_login_btn.setBackground(new Color(0,51,255));
    }//GEN-LAST:event_jLabel_login_btnMouseEntered

    private void jLabel_login_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_login_btnMouseExited
       jLabel_login_btn.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_jLabel_login_btnMouseExited

    private void jLabel_login_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_login_btnMousePressed
        jLabel_login_btn.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED, 
                Color.lightGray, Color.lightGray));
    }//GEN-LAST:event_jLabel_login_btnMousePressed

    private void jLabel_login_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_login_btnMouseReleased
        jLabel_login_btn.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_jLabel_login_btnMouseReleased

    private void jLabel_go_to_main_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_go_to_main_menuMouseClicked
        new RestXInterface.FirstWelcomeScrn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_go_to_main_menuMouseClicked

    private void jLabel_go_to_main_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_go_to_main_menuMouseEntered
       jLabel_go_to_main_menu.setBackground(new Color(180,130,0));
    }//GEN-LAST:event_jLabel_go_to_main_menuMouseEntered

    private void jLabel_go_to_main_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_go_to_main_menuMouseExited
        jLabel_go_to_main_menu.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_jLabel_go_to_main_menuMouseExited

    private void jLabel_go_to_main_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_go_to_main_menuMousePressed
        jLabel_go_to_main_menu.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED, 
                Color.lightGray, Color.lightGray));
    }//GEN-LAST:event_jLabel_go_to_main_menuMousePressed

    private void jLabel_go_to_main_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_go_to_main_menuMouseReleased
        jLabel_go_to_main_menu.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_jLabel_go_to_main_menuMouseReleased

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(FirstWelcomeScrn.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        jLabel_minimize.setBackground(Color.gray);
        jLabel_minimize.setOpaque(true);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        jLabel_minimize.setBackground(new Color(0,0,0,0));
        jLabel_minimize.setOpaque(false);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_minimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMousePressed
        jLabel_minimize.setBackground(Color.darkGray);
    }//GEN-LAST:event_jLabel_minimizeMousePressed

    private void jLabel_minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseReleased
        jLabel_minimize.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_jLabel_minimizeMouseReleased

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        jLabel_close.setBackground(Color.red);
        jLabel_close.setOpaque(true);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        jLabel_close.setBackground(new Color(0,0,0,0));
        jLabel_close.setOpaque(false);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMousePressed

        jLabel_close.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_jLabel_closeMousePressed

    private void jLabel_closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseReleased
        jLabel_close.setBorder(BorderFactory.createEmptyBorder());
        jLabel_close.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_jLabel_closeMouseReleased

    private void jCheckBox_show_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_show_passActionPerformed
               
    }//GEN-LAST:event_jCheckBox_show_passActionPerformed

    private void jCheckBox_show_passItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_show_passItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            jPasswordField.setEchoChar((char) 0);
        } else {
            jPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_show_passItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_show_pass;
    private javax.swing.JLabel jLabel_bg;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_go_to_main_menu;
    private javax.swing.JLabel jLabel_login_btn;
    private javax.swing.JLabel jLabel_login_logo;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_restxname;
    private javax.swing.JLabel jLabel_usrnm;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
