/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestXInterface;

import java.awt.*;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.*;
/**
 *
 * @author shibayanmondal
 */
public class FirstWelcomeScrn extends javax.swing.JFrame {
    
    int pX,pY;
    
    public FirstWelcomeScrn() {
        initComponents();
        this.setSize(626,395);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_avl_upd = new javax.swing.JPanel();
        jLabel_avl_upd = new javax.swing.JLabel();
        jPanel_admin = new javax.swing.JPanel();
        jLabel_admin = new javax.swing.JLabel();
        jPanel_csp = new javax.swing.JPanel();
        jLabel_csp = new javax.swing.JLabel();
        jLabel_restxname = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_wlcm_scr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(getPreferredSize());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_avl_upd.setBackground(new java.awt.Color(51, 153, 255));
        jPanel_avl_upd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_avl_upd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_avl_updMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_avl_updMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_avl_updMouseExited(evt);
            }
        });

        jLabel_avl_upd.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_avl_upd.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_avl_upd.setText("Availability Update");
        jLabel_avl_upd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_avl_updMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_avl_updLayout = new javax.swing.GroupLayout(jPanel_avl_upd);
        jPanel_avl_upd.setLayout(jPanel_avl_updLayout);
        jPanel_avl_updLayout.setHorizontalGroup(
            jPanel_avl_updLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_avl_updLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel_avl_upd, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel_avl_updLayout.setVerticalGroup(
            jPanel_avl_updLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_avl_updLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel_avl_upd)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_avl_upd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 260, 100));
        jPanel_avl_upd.setBackground(new Color(51,153,215,160));
        jPanel_avl_upd.setToolTipText("<html><p>Here, availability of an</p><p>item can be manipulated</p></html>");

        jPanel_admin.setBackground(new java.awt.Color(255, 153, 0));
        jPanel_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_adminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_adminMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_adminMouseReleased(evt);
            }
        });

        jLabel_admin.setBackground(new java.awt.Color(204, 255, 255));
        jLabel_admin.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel_admin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_admin.setText("Admin");
        jLabel_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_adminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_adminMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_adminMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel_adminLayout = new javax.swing.GroupLayout(jPanel_admin);
        jPanel_admin.setLayout(jPanel_adminLayout);
        jPanel_adminLayout.setHorizontalGroup(
            jPanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_adminLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel_admin)
                .addGap(62, 62, 62))
        );
        jPanel_adminLayout.setVerticalGroup(
            jPanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_adminLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel_admin)
                .addGap(84, 84, 84))
        );

        getContentPane().add(jPanel_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 210, 210));
        jPanel_admin.setBackground(new Color(255,153,0, 160));
        jPanel_admin.setToolTipText("<html><p>Admin can add, delete, modify</p><p>items and manipulate data</p></html>");

        jPanel_csp.setBackground(new java.awt.Color(102, 204, 0));
        jPanel_csp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_csp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_cspMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_cspMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_cspMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_cspMousePressed(evt);
            }
        });

        jLabel_csp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_csp.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_csp.setText("Customer Service Portal");
        jLabel_csp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cspMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_cspMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_cspLayout = new javax.swing.GroupLayout(jPanel_csp);
        jPanel_csp.setLayout(jPanel_cspLayout);
        jPanel_cspLayout.setHorizontalGroup(
            jPanel_cspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_csp, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_cspLayout.setVerticalGroup(
            jPanel_cspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_cspLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel_csp)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel_csp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 260, 100));
        jPanel_csp.setBackground(new Color(102,204,0,160));
        jPanel_csp.setToolTipText("<html><p>This portal is for</p><p>generating bill and print</p></html>");

        jLabel_restxname.setBackground(new java.awt.Color(153, 255, 153));
        jLabel_restxname.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel_restxname.setForeground(new java.awt.Color(204, 0, 102));
        jLabel_restxname.setText("Welcome to RestX");
        jLabel_restxname.setName(""); // NOI18N
        getContentPane().add(jLabel_restxname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 420, 70));
        jLabel_restxname.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white));

        jLabel_minimize.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_minimize.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseReleased(evt);
            }
        });
        getContentPane().add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 30));

        jLabel_close.setBackground(new java.awt.Color(153, 0, 0));
        jLabel_close.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseReleased(evt);
            }
        });
        getContentPane().add(jLabel_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, 30));

        jLabel_wlcm_scr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rest_welcm_img.jpg"))); // NOI18N
        jLabel_wlcm_scr.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel_wlcm_scr.setFocusable(false);
        jLabel_wlcm_scr.setInheritsPopupMenu(false);
        jLabel_wlcm_scr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_wlcm_scrMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_wlcm_scrMouseMoved(evt);
            }
        });
        jLabel_wlcm_scr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_wlcm_scrMousePressed(evt);
            }
        });
        getContentPane().add(jLabel_wlcm_scr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_wlcm_scrMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_wlcm_scrMouseDragged
        this.setLocation(this.getX()+ evt.getX() - pX, 
                this.getY() + evt.getY() - pY);
    }//GEN-LAST:event_jLabel_wlcm_scrMouseDragged

    private void jLabel_wlcm_scrMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_wlcm_scrMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_wlcm_scrMouseMoved

    private void jLabel_wlcm_scrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_wlcm_scrMousePressed
        pX = evt.getX();
        pY = evt.getY();
    }//GEN-LAST:event_jLabel_wlcm_scrMousePressed

    private void jPanel_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_adminMouseClicked
        new RestXInterface.AdminLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel_adminMouseClicked

    private void jLabel_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_adminMouseClicked
        RestXInterface.AdminLogin adp = new RestXInterface.AdminLogin();
        adp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_adminMouseClicked

    private void jPanel_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_adminMouseEntered
//        jPanel_admin.setBorder(BorderFactory.createLineBorder(Color.white, 1));
//        jPanel_admin.setBackground(new Color(0,0,0,50));
//        jLabel_admin.setForeground(Color.white);
    }//GEN-LAST:event_jPanel_adminMouseEntered

    private void jPanel_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_adminMouseExited
//        jPanel_admin.setBorder(BorderFactory.createEmptyBorder());
//        jPanel_admin.setBackground(new Color(255,153,0,160));
//        jLabel_admin.setForeground(new Color(51,51,51)); 
    }//GEN-LAST:event_jPanel_adminMouseExited

    private void jPanel_adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_adminMousePressed
//        jPanel_admin.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED));
    }//GEN-LAST:event_jPanel_adminMousePressed

    private void jPanel_adminMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_adminMouseReleased
//        jPanel_admin.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_jPanel_adminMouseReleased

    private void jLabel_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_adminMouseEntered

    }//GEN-LAST:event_jLabel_adminMouseEntered
    
    private void jLabel_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_adminMouseExited

    }//GEN-LAST:event_jLabel_adminMouseExited

    private void jLabel_adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_adminMousePressed
//        jPanel_admin.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED));
    }//GEN-LAST:event_jLabel_adminMousePressed

    private void jLabel_adminMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_adminMouseReleased
//        jPanel_admin.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_jLabel_adminMouseReleased

    private void jPanel_cspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_cspMouseClicked
        new RestXInterface.CustomerPortal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel_cspMouseClicked

    private void jPanel_avl_updMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_avl_updMouseClicked
        new RestXInterface.AvailabilityUpdate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel_avl_updMouseClicked

    private void jPanel_cspMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_cspMouseEntered
//        jPanel_csp.setBorder(BorderFactory.createLineBorder(Color.white, 1));
//        jPanel_csp.setBackground(new Color(0,0,0,50));
//        jLabel_csp.setForeground(Color.white);
    }//GEN-LAST:event_jPanel_cspMouseEntered

    private void jPanel_cspMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_cspMouseExited
//        jPanel_csp.setBorder(BorderFactory.createEmptyBorder());
//        jPanel_csp.setBackground(new Color(255,51,255,160));
//        jLabel_csp.setForeground(new Color(51,51,51)); 
    }//GEN-LAST:event_jPanel_cspMouseExited

    private void jLabel_cspMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cspMousePressed

    }//GEN-LAST:event_jLabel_cspMousePressed

    private void jPanel_cspMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_cspMousePressed

    }//GEN-LAST:event_jPanel_cspMousePressed

    private void jPanel_avl_updMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_avl_updMouseEntered
//        jPanel_avl_upd.setBorder(BorderFactory.createLineBorder(Color.white, 1));
//        jPanel_avl_upd.setBackground(new Color(0,0,0,50));
//        jLabel_avl_upd.setForeground(Color.white);
    }//GEN-LAST:event_jPanel_avl_updMouseEntered

    private void jPanel_avl_updMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_avl_updMouseExited
//        jLabel_avl_upd.setBorder(BorderFactory.createEmptyBorder());
//        jLabel_avl_upd.setBackground(new Color(51,153,215,160));
//        jLabel_avl_upd.setForeground(new Color(51,51,51)); 
    }//GEN-LAST:event_jPanel_avl_updMouseExited

    private void jLabel_cspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cspMouseClicked
        new RestXInterface.CustomerPortal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_cspMouseClicked

    private void jLabel_avl_updMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_avl_updMouseClicked
        new RestXInterface.AvailabilityUpdate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_avl_updMouseClicked

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(FirstWelcomeScrn.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        jLabel_minimize.setBackground(Color.gray);
        jLabel_minimize.setOpaque(true);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        jLabel_minimize.setBackground(new Color(0,0,0,0));
        jLabel_minimize.setOpaque(false);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_minimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMousePressed
        jLabel_minimize.setBackground(Color.darkGray);
    }//GEN-LAST:event_jLabel_minimizeMousePressed

    private void jLabel_minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseReleased
        jLabel_minimize.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_jLabel_minimizeMouseReleased

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        jLabel_close.setBackground(Color.red);
        jLabel_close.setOpaque(true);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        jLabel_close.setBackground(new Color(0,0,0,0));
        jLabel_close.setOpaque(false);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMousePressed

        jLabel_close.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_jLabel_closeMousePressed

    private void jLabel_closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseReleased
        jLabel_close.setBorder(BorderFactory.createEmptyBorder());
        jLabel_close.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_jLabel_closeMouseReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstWelcomeScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstWelcomeScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstWelcomeScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstWelcomeScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        DBConnect.DBConnect.getConnection();
        /* Create and display the form */
        
        Splash sp = new Splash();
        java.awt.EventQueue.invokeLater(() -> {
            sp.setVisible(true);
        });
        FirstWelcomeScrn new_scr = new FirstWelcomeScrn();
        for (int i = 0; i <= 100; i++) {
            try {
                Thread.sleep(20);
            } catch (InterruptedException ex) {
                Logger.getLogger(FirstWelcomeScrn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        new Splash().setVisible(false);
        sp.dispose();
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(FirstWelcomeScrn.class.getName()).log(Level.SEVERE, null, ex);
        }
        new_scr.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_admin;
    private javax.swing.JLabel jLabel_avl_upd;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_csp;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_restxname;
    private javax.swing.JLabel jLabel_wlcm_scr;
    private javax.swing.JPanel jPanel_admin;
    private javax.swing.JPanel jPanel_avl_upd;
    private javax.swing.JPanel jPanel_csp;
    // End of variables declaration//GEN-END:variables
}
